# Generated by Django 3.0.4 on 2020-05-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalHome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_questions',
            name='marks_carry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='app_questions',
            name='notes',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='app_questions',
            name='opt1_desc',
            field=models.CharField(default='NA', max_length=4000),
        ),
        migrations.AddField(
            model_name='app_questions',
            name='opt2_desc',
            field=models.CharField(default='NA', max_length=4000),
        ),
        migrations.AddField(
            model_name='app_questions',
            name='opt3_desc',
            field=models.CharField(default='NA', max_length=4000),
        ),
        migrations.AddField(
            model_name='app_questions',
            name='opt4_desc',
            field=models.CharField(default='NA', max_length=4000),
        ),
        migrations.AddField(
            model_name='app_questions',
            name='opt5_desc',
            field=models.CharField(default='NA', max_length=4000),
        ),
        migrations.AddField(
            model_name='app_questions',
            name='opt6_desc',
            field=models.CharField(default='NA', max_length=4000),
        ),
        migrations.AddField(
            model_name='app_questions',
            name='qdesc',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app_questions',
            name='qtype',
            field=models.CharField(default='OBJ', max_length=10),
        ),
        migrations.AlterField(
            model_name='app_questions',
            name='qno',
            field=models.IntegerField(),
        ),
    ]
