# Generated by Django 3.0.4 on 2020-05-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalHome', '0002_auto_20200522_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_questions',
            name='dummy',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
