# Generated by Django 3.0.4 on 2020-05-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalHome', '0003_app_questions_dummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='acc_questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField()),
                ('qdesc', models.CharField(max_length=2000)),
                ('qtype', models.CharField(default='OBJ', max_length=10)),
                ('opt1_desc', models.CharField(default='NA', max_length=4000)),
                ('opt2_desc', models.CharField(default='NA', max_length=4000)),
                ('opt3_desc', models.CharField(default='NA', max_length=4000)),
                ('opt4_desc', models.CharField(default='NA', max_length=4000)),
                ('opt5_desc', models.CharField(default='NA', max_length=4000)),
                ('opt6_desc', models.CharField(default='NA', max_length=4000)),
                ('marks_carry', models.IntegerField(default=0)),
                ('notes', models.CharField(max_length=400, null=True)),
            ],
            options={
                'db_table': 'acc_questions',
            },
        ),
        migrations.DeleteModel(
            name='app_questions',
        ),
    ]
