# Generated by Django 3.0.4 on 2020-05-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalHome', '0004_auto_20200528_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_questions',
            name='qdesc',
            field=models.TextField(),
        ),
    ]
