# Generated by Django 3.0.4 on 2020-05-29 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortalHome', '0005_auto_20200528_0839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='acc_questions',
        ),
    ]
